# Nastavení pro nasazení na Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Aby PWA fungovala správně, service worker se nemá kešovat
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
